### ISSUE TITLE
Link to ISO proposal

### ISSUE THREAD

**Issue by KantarBruceAdams** [mpark/patterns#8]
I think it would be useful to add at least a related work link to your ISO proposal (i.e. https://github.com/mpark/wg21 & http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1260r0.pdf ) on the front page.

A discussion of how the two differ would be even better.
For instance I note that the "WHEN clause" of this project becomes a pattern guard in the proposal.

A related but distinct issue is the relationship between this and the earlier Mach7. Why use one rather than the other?

**Comment by mpark** [comment]
> I think it would be useful to add at least a related work link to your ISO proposal (i.e. https://github.com/mpark/wg21 & http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1260r0.pdf ) on the front page.

Thanks! I've added related C++ committee papers under "Related Work"

> A discussion of how the two differ would be even better.
> For instance I note that the "WHEN clause" of this project becomes a pattern guard in the proposal.

> A related but distinct issue is the relationship between this and the earlier Mach7. Why use one rather than the other?

I'll perhaps take some time to do this in the future but at the moment I don't have the bandwidth to work on this 😕
