### ISSUE TITLE
example function fails to compile 

### ISSUE THREAD

**Issue by diegor8** [mpark/patterns#9]
![Screenshot from 2019-05-11 13-05-01](https://user-images.githubusercontent.com/9205622/57572787-76dab980-73ed-11e9-9022-e7ae9eb2b44d.png)

**Comment by mpark** [comment]
Hi @diegor8! Could you share what compiler you're using to compile this?

**Comment by diegor8** [comment]
I use fedora 29 , so my system's default conpiler is g++ 8 .After I got the error I tried configuring my project to use clang , but i don't know if i was succesful

**Comment by diegor8** [comment]
to be precise : 

> [diegorosario@localhost ~]$ g++ --version
g++ (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

>[diegorosario@localhost ~]$ clang --version
clang version 7.0.1 (Fedora 7.0.1-6.fc29)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
[diegorosario@localhost ~]$ 

and i tried to set clang this way 
> set(CMAKE_CXX_COMPILER:FILEPATH /usr/bin/clang++ )

**Comment by diegor8** [comment]
@mpark this project does not rely on any dependencies , right ?

**Comment by mpark** [comment]
Hm... no, it doesn’t. I’ll take a look at this on Monday, as I’m traveling after C++Now this weekend!

**Comment by diegor8** [comment]
i upgraded to fedora 30 and i dont get the problem anymore , so the issue likely stems from the gcc or clang version used by fedora 29

> clang --version
clang version 8.0.0 (Fedora 8.0.0-1.fc30)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
> g++  --version
g++ (GCC) 9.1.1 20190503 (Red Hat 9.1.1-1)
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by mpark** [comment]
I was able to reproduce with a Travis CI job: https://travis-ci.org/mpark/patterns/jobs/533248856

**Comment by diegor8** [comment]
shall i try to submit a bug report or do you have the time to do it ?

**Comment by mpark** [comment]
I don't have time at the moment to produce a minimal repro to submit a bug. If you have time to do so, that would be great!
